In [1]:
import pandas as pd

In [26]:
df = pd.read_csv('netflix_titles.csv')

In [44]:
import sqlalchemy as sal

engine = sal.create_engine(
    "mssql+pyodbc://LAPTOP-4L14UMHG\\SQLEXPRESS/master?driver=ODBC+Driver+17+for+SQL+Server"
)

conn = engine.connect()

print("Connected Successfully!")

Connected Successfully!

In [45]:
df.to_sql('netflix_raw', con=conn , index=False, if_exists = 'append')
conn.close()

In [29]:
len(df)

8807

In [30]:
df[df.show_id=='s5023']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5022,s5023,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...

In [31]:
df.show_id.str.len()

0       2
1       2
2       2
3       2
4       2
       ..
8802    5
8803    5
8804    5
8805    5
8806    5
Name: show_id, Length: 8807, dtype: int64

In [32]:
max(df.show_id.str.len())

5

In [33]:
max(df.type.str.len())

7

In [34]:
max(df.title.str.len())

104

In [35]:
max(df.director.str.len())

208.0

In [36]:
max(df.cast.str.len())

nan

In [37]:
max(df.cast.dropna().str.len())  #drop the null value

771

In [38]:
max(df.country.dropna().str.len())

123

In [39]:
max(df.date_added.dropna().str.len())

19

In [40]:
max(df.rating.dropna().str.len())

8

In [41]:
max(df.duration.dropna().str.len())

10

In [42]:
max(df.listed_in.dropna().str.len())

79

In [43]:
max(df.description.dropna().str.len())

248

In [46]:
df[df.show_id=='s5023']

,show_id,type,title,director,cast,country,date_added,release_year,rating,duration,listed_in,description
5022,s5023,Movie,반드시 잡는다,Hong-seon Kim,Baek Yoon-sik,South Korea,"February 28, 2018",2017,TV-MA,110 min,"Dramas, International Movies, Thrillers",After people in his town start turning up dead...